create table tb_sales (id int8 generated by default as identity, amount float8, date date, deals int4, visited int4, seller_id int8, primary key (id));
create table tb_sellers (id int8 generated by default as identity, name varchar(255), primary key (id));
create table tb_sellers_sales (seller_id int8 not null, sales_id int8 not null);
alter table if exists tb_sellers_sales add constraint UK_1oqi8ketafl62ptnwa2togilf unique (sales_id);
alter table if exists tb_sales add constraint FKp0nn0oixeiw2fq3jivj6vnsu foreign key (seller_id) references tb_sellers;
alter table if exists tb_sellers_sales add constraint FKl19pmhcyww30evugghngh5crx foreign key (sales_id) references tb_sales;
alter table if exists tb_sellers_sales add constraint FKa9gx7fpbvyt7tirrs1t9h6spc foreign key (seller_id) references tb_sellers;
